#!/usr/bin/env python3
"""
ROADMAP index/detail pair — generator + drift checker.

STRUCTURAL READ-CAP FIX (2026-09-05, Will-directed). ROADMAP.md was 51,744 B = 1.57x the
32,550 B whole-read budget, and 61% of it was ONE table: 28 genuinely-open threads at
~865 B each. Rotation could not fix it — the content is LIVE, not residue (measured; the
closed-mis-filed rows were only 6%).

THE SPLIT:
  ROADMAP.md            -> bounded INDEX (Thread | Next Step | Last Touched). BOOT-READ.
  ROADMAP_THREADS.md    -> full 4-col table verbatim (adds the Status narrative). GREP-ONLY.

WHY A SPLIT IS SAFE HERE AND WAS NOT SAFE FOR STUE: CARL ruled against a hot/cold split on
STUE's surface because no coherence checker reaches a sub-agent, so two surfaces would
drift unchecked. CARL HAS a checker. This script is it — and the index is GENERATED from
the detail, so the pair cannot drift by construction, not merely by audit. Same pattern the
desk already uses for thesis/PREDICTIONS.tsv -> PREDICTIONS_MIRROR.md (Check A).

  --rebuild   regenerate the INDEX in ROADMAP.md from ROADMAP_THREADS.md
  --check     exit 1 if the live index block != the block --rebuild would write
              (byte comparison of the RENDERING, not a thread-name set)     [closeout gate]
"""
import io, os, re, sys, subprocess

ROOT = subprocess.check_output(["git","rev-parse","--show-toplevel"]).decode().strip()
D    = os.path.join(ROOT, "AGENTS/CARL")
RM   = os.path.join(D, "ROADMAP.md")
TH   = os.path.join(D, "ROADMAP_THREADS.md")

IDX_START = "<!-- ROADMAP-INDEX:START -- GENERATED by scripts/roadmap_index.py --rebuild. Do not hand-edit; edit ROADMAP_THREADS.md and rebuild. -->"
IDX_END   = "<!-- ROADMAP-INDEX:END -->"

def key(cell):
    """Stable thread identity: strip markdown, collapse whitespace, cap length."""
    t = re.sub(r'[*`~]', '', cell).strip()
    return re.sub(r'\s+', ' ', t)[:90]

def detail_rows():
    if not os.path.exists(TH): return []
    out=[]
    for l in io.open(TH, encoding="utf-8").read().split("\n"):
        if not l.startswith("| "): continue
        c=l.split("|")[1:-1]
        if len(c)<4: continue
        if re.match(r'\s*[-:]+\s*$', c[0]) or c[0].strip().lower().startswith("thread"): continue
        out.append([x.strip() for x in c])
    return out

def build_index(rows):
    L=[IDX_START,
       "",
       f"**{len(rows)} open thread(s).** ⛔ **This is the BOOT-READ surface. The Status narrative lives in `ROADMAP_THREADS.md` — GREP it, never read it whole** (`grep -A2 '<thread name>' AGENTS/CARL/ROADMAP_THREADS.md`).",
       "",
       "| # | Thread | Next Step | Last Touched |",
       "|---|--------|-----------|--------------|"]
    for i,c in enumerate(rows,1):
        nxt=re.sub(r'\s+',' ',re.sub(r'[|]','',c[2])).strip()
        if len(nxt)>150: nxt=nxt[:147].rstrip()+"…"
        thr=re.sub(r'\s+',' ',re.sub(r'[|]','',c[0])).strip()
        if len(thr)>110: thr=thr[:107].rstrip()+"…"
        L.append(f"| {i} | {thr} | {nxt} | {c[3]} |")
    L+=["", IDX_END]
    return "\n".join(L)

def splice(text, block):
    a=text.find(IDX_START)
    if a<0: raise SystemExit("ERROR: index anchors absent from ROADMAP.md — refusing to guess placement.")
    b=text.find(IDX_END, a)
    if b<0: raise SystemExit("ERROR: index END anchor missing — refusing a one-sided splice.")
    return text[:a] + block + text[b+len(IDX_END):]

def main():
    rows=detail_rows()
    if not rows: raise SystemExit("ERROR: no detail rows found in ROADMAP_THREADS.md")
    txt=io.open(RM, encoding="utf-8").read()
    if "--check" in sys.argv:
        # Compare the RENDERING, not a key set (Codex/PROME 2026-09-05: a changed Next Step with the
        # same thread name passed the old name-set check -- a false PASS certifying a stale index).
        # The generator already produces the expected block; any byte difference inside the anchors
        # is drift. Patch built + 8-test-verified by PROME, applied by CARL 2026-09-10.
        if txt.count(IDX_START)!=1 or txt.count(IDX_END)!=1:
            print(f"ROADMAP-INDEX ✗ ANCHORS: START x{txt.count(IDX_START)} END x{txt.count(IDX_END)} -- exactly one of each required")
            sys.exit(1)
        a=txt.find(IDX_START); b=txt.find(IDX_END, a)
        if b<0:
            print("ROADMAP-INDEX ✗ ANCHORS: END anchor precedes START"); sys.exit(1)
        live=txt[a:b+len(IDX_END)]
        want=build_index(rows)
        if live!=want:
            lv, wv = live.split("\n"), want.split("\n")
            diffs=[i for i in range(max(len(lv),len(wv))) if (lv[i] if i<len(lv) else None)!=(wv[i] if i<len(wv) else None)]
            print(f"ROADMAP-INDEX ✗ DRIFT: live index block != regenerated block ({len(diffs)} differing line(s); live {len(lv)} lines, expected {len(wv)})")
            for i in diffs[:6]:
                print(f"   line {i+1:>3} live     : {(lv[i] if i<len(lv) else '<absent>')[:88]}")
                print(f"   line {i+1:>3} expected : {(wv[i] if i<len(wv) else '<absent>')[:88]}")
            print("   fix: python3 AGENTS/CARL/scripts/roadmap_index.py --rebuild")
            sys.exit(1)
        print(f"ROADMAP-INDEX ✓ live index block matches regeneration byte-for-byte ({len(rows)} thread(s))")
        sys.exit(0)
    if "--rebuild" in sys.argv:
        new=splice(txt, build_index(rows))
        io.open(RM+".tmp","w",encoding="utf-8").write(new); os.replace(RM+".tmp", RM)
        print(f"ROADMAP-INDEX rebuilt: {len(rows)} threads · ROADMAP.md now {len(new):,} B")
        sys.exit(0)
    print(__doc__)

if __name__ == "__main__":
    main()
