#!/usr/bin/env python3
"""Regenerate memory/auto/MEMORY.md — the lean, always-loaded auto-memory index.

Claude Code loads only the first ~200 lines / 25 KB of MEMORY.md at boot; topic
files (feedback_*, finding_*, project_*) are read on demand. So the index must
stay terse: one line per memory.

This index is DERIVED from the topic files, not hand-maintained. That kills the
main simultaneous-write conflict point: if two machines both touch MEMORY.md,
the resolution is simply to re-run this script after the merge — the output is
deterministic given the set of topic files present.

Usage:
    python3 scripts/gen_automemory_index.py [store_dir]
Defaults store_dir to <repo>/memory/auto.
"""
import os
import re
import sys
import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_STORE = os.path.join(os.path.dirname(HERE), "memory", "auto")
STORE = os.path.abspath(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_STORE

SKIP = {"MEMORY.md", "README.md"}
ORDER = ["feedback_", "finding_", "project_", "other_"]
TITLES = {
    "feedback_": "Feedback — how to work (behavioral corrections)",
    "finding_": "Findings — patterns & methodological insight",
    "project_": "Projects — initiative state",
    "other_": "Other",
}


def summary(path):
    """Prefer a YAML frontmatter `description:` field; otherwise fall back to the
    first non-empty line with markdown heading marks stripped. Truncated to keep
    the always-loaded index lean."""
    try:
        with open(path, encoding="utf-8") as fh:
            lines = fh.read().splitlines()
    except OSError:
        return "(unreadable)"

    body_start = 0
    # YAML frontmatter is a leading '---' ... '---' block.
    if lines and lines[0].strip() == "---":
        body_start = len(lines)  # if there's no closing fence, treat all as frontmatter
        for i in range(1, len(lines)):
            if lines[i].strip() == "---":
                body_start = i + 1
                break
            m = re.match(r"\s*description\s*:\s*(.+?)\s*$", lines[i])
            if m:
                return m.group(1).strip().strip("\"'")[:120]

    for line in lines[body_start:]:
        s = line.strip()
        if s:
            return re.sub(r"^#+\s*", "", s)[:120]
    return "(empty)"


def bucket(name):
    for p in ORDER[:-1]:
        if name.startswith(p):
            return p
    return "other_"


def main():
    if not os.path.isdir(STORE):
        sys.exit(f"store dir not found: {STORE}")

    files = [
        f for f in sorted(os.listdir(STORE))
        if f.endswith(".md") and f not in SKIP
        and ".conflict-" not in f and not f.startswith(".")
    ]

    groups = {}
    for f in files:
        groups.setdefault(bucket(f), []).append(f)

    out = [
        "# MEMORY — auto-memory index",
        "",
        f"_Generated by `scripts/gen_automemory_index.py` on {datetime.date.today()}. "
        "Do not hand-edit — re-run the script. (Re-running is also the fix for any "
        "MEMORY.md merge conflict.)_",
        "",
        f"{len(files)} entries. This index loads at every boot; topic files load on demand.",
        "",
    ]
    for p in ORDER:
        if p not in groups:
            continue
        out.append(f"## {TITLES[p]}")
        out.append("")
        for f in groups[p]:
            out.append(f"- `[[{f[:-3]}]]` — {summary(os.path.join(STORE, f))}")
        out.append("")

    text = "\n".join(out).rstrip() + "\n"
    with open(os.path.join(STORE, "MEMORY.md"), "w", encoding="utf-8") as fh:
        fh.write(text)

    nlines = text.count("\n")
    print(f"Wrote {os.path.join(STORE, 'MEMORY.md')}: {len(files)} entries, {nlines} lines.")
    if nlines > 180:
        print(
            f"WARNING: index is {nlines} lines — Claude loads only ~200/25KB at boot. "
            "Consolidate or retire low-value entries."
        )


if __name__ == "__main__":
    main()
