#!/usr/bin/env python3
"""CRE-by-property-type cohort pull — balances (RC-C), past-due/nonaccrual (RC-N), charge-offs (RI-B Part I).

Built 2026-09-26 for the CRE-vulnerability selection (reports/2026-09-26_CRE_vulnerability_top3.md).
Reuses mi3_cohort_screen.py's FFIEC CDR REST/JWT machinery (creds, facsimile, parse, pick, COHORT).

Property types (Call Report definitions):
  con = 1-4 family construction F158 + other construction/land F159   (RC-N F172/F173 · F174/F175 · F176/F177; RI-B C891/C893, rec C892/C894)
  mf  = multifamily 1460                                                (RC-N 3499 · 3500 · 3501 — NOT 3493-3495, which are FARMLAND; RI-B 3588/3589)
  oo  = owner-occupied nonfarm nonresidential F160                      (RC-N F178 · F180 · F182; RI-B C895/C896)
  noo = other (non-owner-occupied) nonfarm nonresidential F161          (RC-N F179 · F181 · F183; RI-B C897/C898)
RC-N columns: A = 30-89 days past due, B = 90+ still accruing, C = nonaccrual.
RI-B values are YEAR-TO-DATE; quarterly flows are YTD differences with the Q1 reset.

Guards: a missing MDRM is None, never 0 (zero != unknown). Output rows carry the RSSD and period.
Office is NOT separable in the Call Report: it sits inside `noo` (and `oo`). Say so wherever `noo` is quoted as "office".
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import mi3_cohort_screen as m  # noqa: E402

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "AGENTS/REGINALD/workbook/CRE_RCN_COHORT.tsv"
QUARTERS = ["6/30/2025", "9/30/2025", "12/31/2025", "3/31/2026", "6/30/2026"]
NEXT_DUE = "2026-11-07"

FIELDS = {
    "loans_k": ["2122"], "nonaccrual_total_k": ["1403"], "acl_k": ["3123"],
    "bal_con_k": ["F158", "F159"], "bal_mf_k": ["1460"], "bal_oo_k": ["F160"], "bal_noo_k": ["F161"],
    "pd3089_con_k": ["F172", "F173"], "pd90_con_k": ["F174", "F175"], "na_con_k": ["F176", "F177"],
    "pd3089_mf_k": ["3499"], "pd90_mf_k": ["3500"], "na_mf_k": ["3501"],
    "pd3089_oo_k": ["F178"], "pd90_oo_k": ["F180"], "na_oo_k": ["F182"],
    "pd3089_noo_k": ["F179"], "pd90_noo_k": ["F181"], "na_noo_k": ["F183"],
    "co_ytd_con_k": ["C891", "C893"], "rec_ytd_con_k": ["C892", "C894"],
    "co_ytd_mf_k": ["3588"], "rec_ytd_mf_k": ["3589"],
    "co_ytd_oo_k": ["C895"], "rec_ytd_oo_k": ["C896"],
    "co_ytd_noo_k": ["C897"], "rec_ytd_noo_k": ["C898"],
    "co_ytd_total_k": ["4635"], "rec_ytd_total_k": ["4605"],
    # RC-M item 3 — foreclosed real estate (OREO). The matrix credit leg reads nonaccrual RCON1403, which
    # EXCLUDES OREO, so a bank that forecloses rather than holds nonaccruals looks cleaner than it is (OZK, 9/26).
    "oreo_total_k": ["2150"], "oreo_con_k": ["5508"], "oreo_mf_k": ["5511"], "oreo_nfnr_k": ["5512"],
}


def main():
    user, token = m.creds()
    rows = []
    for tk, rssd, *_ in m.COHORT:
        for q in QUARTERS:
            sdf = m.facsimile(user, token, rssd, q)
            if not sdf:
                sys.exit(f"FETCH FAILED {tk} {rssd} {q} — nothing written")
            d = m.parse(sdf)
            row = {"ticker": tk, "rssd": rssd, "quarter": q}
            for k, codes in FIELDS.items():
                prefixes = ("RIAD",) if k.startswith(("co_", "rec_")) else m.PREFIXES
                v, _ = m.pick(d, codes, prefixes)
                row[k] = "" if v is None else v
            rows.append(row)
    cols = ["ticker", "rssd", "quarter"] + list(FIELDS)
    with open(OUT, "w", newline="") as fh:
        fh.write("# Last real data refresh: 2026-09-26 — FFIEC CDR REST/JWT RetrieveFacsimile/SDF, 14 MI3-cohort banks x "
                 f"{len(QUARTERS)} quarters, all at the FFIEC primary. Generated by scripts/cre_rcn_cohort.py. "
                 "Units $K. RI-B columns are YEAR-TO-DATE. Blank = MDRM absent (unknown), never zero. "
                 "Office is not separable in the Call Report (inside noo/oo).\n")
        fh.write(f"# Cadence: SCHEDULED next_due={NEXT_DUE} — quarterly, same clock as MI3_COHORT.tsv; roll QUARTERS then.\n")
        fh.write("\t".join(cols) + "\n")
        for r in rows:
            fh.write("\t".join(str(r[c]) for c in cols) + "\n")
    print(f"wrote {len(rows)} rows -> {OUT}")


if __name__ == "__main__":
    main()
